[envs]
global_foo = "bar"
global_env = "staging"

[services]

[services."Deno panic test 001"]
cmd = "testing/deno-bins/fail"
expo_backoff = true

[services."Deno panic test 002"]
cmd = "testing/deno-bins/fail"
expo_backoff = true

[services."Deno panic test 003"]
cmd = "testing/deno-bins/fail"
expo_backoff = true

[services."Deno Test API 001"]
cmd = "testing/deno-bins/deno-bins"
envs = { "PORT" = "3006" }
restart_on_success = true
proxy = "malted.dev/p1"

[services."Deno Test API 002"]
cmd = "testing/deno-bins/deno-bins"
restart_on_success = true
proxy = "malted.dev/p1"
envs = { "PORT" = "3007" }

[services."Deno Test API 003"]
cmd = "testing/deno-bins/deno-bins"
restart_on_success = true
proxy = "malted.dev/p1"
envs = { "PORT" = "3008" }

[services."Deno Test API 004"]
cmd = "testing/deno-bins/deno-bins"
restart_on_success = true
proxy = "malted.dev/p1"
envs = { "PORT" = "3009" }

[services."Deno Test API 005"]
cmd = "testing/deno-bins/deno-bins"
restart_on_success = true
envs = { "PORT" = "3010" }

[services."Deno Test API 006"]
cmd = "testing/deno-bins/deno-bins"
restart_on_success = true
envs = { "PORT" = "3011" }
