[envs]
global_foo = "bar"
global_env = "staging"

[services]

# [services.fails]
# path = "testing/fails/target/release/fails"
# max_restarts = 3

# [services.fails2]
# path = "testing/fails/target/release/fails"

# [services.envs]
# path = "testing/envs/target/release/envs"
# envs = { "PMRSONE" = "WOO! IT WORKED!", "PMRS TWO" = "the space worked! 🥺" }
# wd = "logs"

[services."Deno panic test 001"]
path = "testing/deno-bins/deno-bins"
envs = { "PORT" = "3005" }

[services."Deno panic test 002"]
path = "testing/deno-bins/fail"
expo_backoff = true
restart_delay = 5
